export const roles = [
  {
    start: "Nov 2021",
    end: "Present",
    position: "Senior Full Stack Engineer",
    companyName: "Beem | Eftpos | AP+",
    description: "",
    icon: "",
  },
  {
    start: "Jul 2021",
    end: "Nov 2021",
    position: "Senior Full Stack Engineer",
    companyName: "Ooh! Media",
    description: "",
    icon: "",
  },
  {
    start: "Jun 2020",
    end: "Jul 2021",
    position: "Senior Full Stack Engineer",
    companyName: "Enboarder",
    description: "",
    icon: "",
    promotion: true,
  },
  {
    start: "Nov 2019",
    end: "Jun 2020",
    position: "Full Stack Engineer",
    companyName: "Enboarder",
    description: "",
    icon: "",
  },
  {
    start: "Jul 2021",
    end: "Nov 2019",
    position: "Full Stack Engineer",
    companyName: "Cloud.IQ",
    description: "",
    icon: "",
  },
  {
    start: "Mar 2013",
    end: "Apr 2019",
    position: "Founder",
    companyName: "ReCreateideas.com",
    description: "",
    icon: "",
  },
  {
    start: "Mar 2015",
    end: "Oct 2017",
    position: "Fullstack Developer",
    companyName: "Vivid Social",
    description: "",
    icon: "",
  },
  {
    start: "May 2012",
    end: "Feb 2015",
    position: "Owner, Venue Manager, Licensee",
    companyName: "Blacksmith Cafes and Bars",
    description: "",
    icon: "",
  },
  {
    start: "Apr 2009",
    end: "Oct 2009",
    position: "Grad / Junior Software Developer",
    companyName: "Ericsson IT Solutions & Services SpA",
    description: "",
    icon: "",
  },
];
