import { CommonActionTypes } from '@types';

const types: CommonActionTypes = {
    SET_IS_DEV: 'SET_IS_DEV',
    SET_IS_ELECTRON: 'SET_IS_ELECTRON',
    GET_SERVICE_PORTS_PENDING: 'GET_SERVICE_PORTS_PENDING',
    GET_SERVICE_PORTS_SUCCESS: 'GET_SERVICE_PORTS_SUCCESS',
    SET_SERVICE_PORTS: 'SET_SERVICE_PORTS',
    GET_SERVICE_PORTS_SKIPPED: 'GET_SERVICE_PORTS_SKIPPED',
};

export default types;
