import { AuthActionTypes } from "src/redux";

const types: AuthActionTypes = {
  EXCHANGE_TOKEN_FOR_USER_DETAILS_PENDING:
    "EXCHANGE_TOKEN_FOR_USER_DETAILS_PENDING",
  EXCHANGE_TOKEN_FOR_USER_DETAILS_SUCCESS:
    "EXCHANGE_TOKEN_FOR_USER_DETAILS_SUCCESS",
  EXCHANGE_TOKEN_FOR_USER_DETAILS_ERROR:
    "EXCHANGE_TOKEN_FOR_USER_DETAILS_ERROR",
  SAVE_USER_DATA: "SAVE_USER_DATA",
};

export default types;
