import { AuthActionTypes } from "src/redux";

const types: AuthActionTypes = {
  EXCHANGE_CODE_FOR_TOKENS_PENDING: "EXCHANGE_CODE_FOR_TOKENS_PENDING",
  EXCHANGE_CODE_FOR_TOKENS_SUCCESS: "EXCHANGE_CODE_FOR_TOKENS_SUCCESS",
  EXCHANGE_CODE_FOR_TOKENS_ERROR: "EXCHANGE_CODE_FOR_TOKENS_ERROR",
  SAVE_USER_DATA: "SAVE_USER_DATA",
};

export default types;
